In [1]:
import pandas as pd
#pd.set_option("display.max_rows", None)
import numpy as np
import datetime
import time

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
pd.set_option('display.max_columns', None)

import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff
import dash
import dash_core_components as dcc
import dash_html_components as html

import ibmdata

In [2]:
DAYSBACK = 365
VMIN_CORNER = '_H2_0P50V_BLOCK'
VNOM_CORNER = '_H2_0P65V_BLOCK'
VMAX_CORNER = '_H2_1P05V_BLOCK'
QUERY = f"""
WITH cte AS(
    (SELECT LEFT(lot_id, 5) AS lot_id_base, lot_Id, wafer_Id, family_Code, tw.Calcdefs AS Sail, tw.Last_test_date AS date,
        unitcell_X - 1 AS retx, unitcell_Y AS rety, SUBSTR(parm_Label, 10,5) AS corner,
        tw.testProgramName||RIGHT(parm_Label,8) AS label, 
        parmYield as yield
    FROM DMIW.ChipParmFactR cpfr
        JOIN DMIW_SYSTEMS.TestParm tp ON tp.testParmKey = cpfr.testParmKey
        JOIN DMIW_SYSTEMS.Geography g ON g.geographyKey = cpfr.geographyKey
        JOIN DMIW_SYSTEMS.TestedWafer tw ON tw.testedWaferKey = cpfr.testedWaferKey
    WHERE Last_test_date >= (current date - {DAYSBACK} days)
        AND Tech_id = '7HPP' AND Level = 'H2' AND tw.Calcdefs IN ('SSL21', 'SSL31')
        AND cpfr.parmValue IS NOT null AND ABS(parmValue) < 1e25 
        AND (UCASE(SUBSTR(tp.parm_Label,6,15)) IN ('{VMIN_CORNER}','{VNOM_CORNER}'))
        AND ((unitcell_X - 1) || '_' || unitcell_Y NOT IN ('-2_-1','1_8','2_9','2_10','3_10','4_11','5_11','6_11','7_11','9_10','10_9','11_8','1_4','2_3','3_2','4_1','5_1','7_1','9_2','10_3','11_4'))
        AND SUBSTR(tp.parm_Label,5,1) = RIGHT(tw.testProgramName,1)
        AND RIGHT(tp.parm_Label,7) IN ('Block26','Block27','Block28')
        AND family_Code = 'Q5'
    ORDER BY lot_Id, wafer_Id, parm_Label)
    
    UNION ALL
    
    (SELECT LEFT(lot_id, 5) AS lot_id_base, lot_Id, wafer_Id, family_Code, tw.Calcdefs AS Sail, tw.Last_test_date AS date,
        unitcell_X AS retx, unitcell_Y AS rety, SUBSTR(parm_Label, 10,5) AS corner,
        tw.testProgramName||RIGHT(parm_Label,8) AS label,
        parmYield as yield
    FROM DMIW.ChipParmFactR cpfr
        JOIN DMIW_SYSTEMS.TestParm tp ON tp.testParmKey = cpfr.testParmKey
        JOIN DMIW_SYSTEMS.Geography g ON g.geographyKey = cpfr.geographyKey
        JOIN DMIW_SYSTEMS.TestedWafer tw ON tw.testedWaferKey = cpfr.testedWaferKey
    WHERE Last_test_date >= (current date - {DAYSBACK} days)
        AND Tech_id = '7HPP' AND Level = 'H2' AND tw.Calcdefs IN ('SSL21', 'SSL31')
        AND cpfr.parmValue IS NOT null AND ABS(parmValue) < 1e25 
        AND (UCASE(SUBSTR(tp.parm_Label,6,15)) IN ('{VMIN_CORNER}','{VNOM_CORNER}'))
        AND ((unitcell_X) || '_' || unitcell_Y NOT IN ('1_7','2_9','3_10','4_11','5_11','6_12','7_12','9_11','10_11','11_10','12_8','12_5','11_3','10_2','9_2','6_1','5_2','4_2','3_3','2_4'))
        AND SUBSTR(tp.parm_Label,5,1) = RIGHT(tw.testProgramName,1)
        AND RIGHT(tp.parm_Label,7) IN ('Block26','Block27','Block28')
        AND family_Code = 'Q6'
    ORDER BY lot_Id, wafer_Id, parm_Label)
),
cte2 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, corner, MAX(date) AS date, retx, rety, MIN(yield) AS yield
    FROM cte
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner, retx, rety
),
cte3 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, corner, MAX(date) AS date, AVG(yield) AS yield
    FROM cte2
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner
),
cte4 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, MAX(date) AS date, 
    MAX(CASE WHEN corner = '0p50V' THEN yield ELSE -100 END) AS vmin_yield,
    MAX(CASE WHEN corner = '0p65V' THEN yield ELSE -100 END) AS vnom_yield
    FROM cte3
    GROUP BY lot_id_base, lot_id, wafer_id, family_code
)

SELECT lot_id_base, lot_id, wafer_id, family_code, Max(date) AS date,
    AVG(vnom_yield - vmin_yield) AS vmin_loss
FROM cte4
GROUP BY lot_id_base, lot_id, wafer_id, family_code
"""
df = ibmdata.isdw.query(QUERY)
df['vmin_loss'] = df['vmin_loss'].astype(float).round(2)

In [3]:
df

     lot_id_base    lot_id  wafer_id family_code        date  vmin_loss
0          A1AVP  A1AVPA.1  A1AVP-01          Q6  2021-05-08       0.00
1          A1AVP  A1AVPA.1  A1AVP-02          Q6  2021-05-08       0.00
2          A1AVP  A1AVPA.1  A1AVP-03          Q6  2021-05-08       0.00
3          A1AVP   A1AVP.1  A1AVP-04          Q6  2021-05-07       1.25
4          A1AVP  A1AVPA.1  A1AVP-05          Q6  2021-05-08       0.00
...          ...       ...       ...         ...         ...        ...
2296       AZB45   AZB45.1  AZB45-19          Q5  2021-08-12       0.00
2297       AZB45   AZB45.1  AZB45-20          Q5  2021-08-12       0.00
2298       AZB45   AZB45.1  AZB45-21          Q5  2021-08-12       0.00
2299       AZB45   AZB45.1  AZB45-22          Q5  2021-08-12       0.00
2300       AZB45   AZB45.1  AZB45-23          Q5  2021-08-12       0.00

[2301 rows x 6 columns]

In [4]:
df.to_csv('~/Downloads/temp.csv')

In [2]:
DAYSBACK = 365
VMIN_CORNER = '_H2_0P50V_BLOCK'
VNOM_CORNER = '_H2_0P65V_BLOCK'
VMAX_CORNER = '_H2_1P05V_BLOCK'
QUERY = f"""
WITH cte AS(
    SELECT LEFT(lot_id, 5) AS lot_id_base, lot_Id, wafer_Id, family_Code, tw.Calcdefs AS Sail, tw.Last_test_date AS date,
        unitcell_X AS retx, unitcell_Y AS rety, SUBSTR(parm_Label, 10,5) AS corner,
        tw.testProgramName||RIGHT(parm_Label,8) AS label, 
        parmYield as yield
    FROM DMIW.ChipParmFactR cpfr
        JOIN DMIW_SYSTEMS.TestParm tp ON tp.testParmKey = cpfr.testParmKey
        JOIN DMIW_SYSTEMS.Geography g ON g.geographyKey = cpfr.geographyKey
        JOIN DMIW_SYSTEMS.TestedWafer tw ON tw.testedWaferKey = cpfr.testedWaferKey
    WHERE Last_test_date >= (current date - {DAYSBACK} days)
        AND Tech_id = '7HPP' AND Level = 'H2' AND tw.Calcdefs IN ('SSL11','SSL21', 'SSL31')
        AND cpfr.parmValue IS NOT null AND ABS(parmValue) < 1e25 
        AND (UCASE(SUBSTR(tp.parm_Label,6,15)) IN ('{VMIN_CORNER}','{VNOM_CORNER}'))
        AND ((unitcell_X - 1) || '_' || unitcell_Y NOT IN ('5_12','6_12','7_12','8_12','4_11','10_11','3_10','11_10','2_9','12_9','2_4','12_4','3_3','11_3','4_2','10_2','5_1','6_1','7_1','8_1'))
        AND SUBSTR(tp.parm_Label,5,1) = RIGHT(tw.testProgramName,1)
        AND RIGHT(tp.parm_Label,7) IN ('Block26','Block27','Block28')
        --AND family_Code = 'XQ'
        AND family_Code = 'X2'
    ORDER BY lot_Id, wafer_Id, parm_Label
),
cte2 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, corner, MAX(date) AS date, retx, rety, MIN(yield) AS yield
    FROM cte
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner, retx, rety
),
cte3 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, corner, MAX(date) AS date, AVG(yield) AS yield
    FROM cte2
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner
),
cte4 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, MAX(date) AS date, 
    MAX(CASE WHEN corner = '0p50V' THEN yield ELSE -100 END) AS vmin_yield,
    MAX(CASE WHEN corner = '0p65V' THEN yield ELSE -100 END) AS vnom_yield
    FROM cte3
    GROUP BY lot_id_base, lot_id, wafer_id, family_code
)

SELECT lot_id_base, lot_id, wafer_id, family_code, Max(date) AS date,
    AVG(vnom_yield - vmin_yield) AS vmin_loss
FROM cte4
GROUP BY lot_id_base, lot_id, wafer_id, family_code
"""
df = ibmdata.isdw.query(QUERY)
df['vmin_loss'] = df['vmin_loss'].astype(float).round(2)

In [3]:
df.to_csv("~/Downloads/tmp.csv")

In [5]:
df[df.wafer_id == 'AZBAU-12']

Empty DataFrame
Columns: [lot_id_base, lot_id, wafer_id, family_code, date, vmin_loss]
Index: []

In [3]:
df

    lot_id_base    lot_id  wafer_id family_code        date  vmin_loss
0         AZAVY   AZAVY.1  AZAVY-10          XQ  2021-06-14       0.00
1         AZAVY   AZAVY.1  AZAVY-11          XQ  2021-06-04       4.21
2         AZAW7  AZAW7A.1  AZAW7-15          XQ  2021-07-27       0.00
3         AZB4U   AZB4U.1  AZB4U-07          XQ  2021-08-15       0.38
4         AZB4U   AZB4U.1  AZB4U-08          XQ  2021-08-15       0.38
..          ...       ...       ...         ...         ...        ...
387       AZBB6   AZBB6.1  AZBB6-21          XQ  2021-08-28       0.00
388       AZBB6   AZBB6.1  AZBB6-22          XQ  2021-08-28       0.00
389       AZBB6   AZBB6.1  AZBB6-23          XQ  2021-08-28       0.00
390       AZBB6   AZBB6.1  AZBB6-24          XQ  2021-08-28       0.38
391       AZBB6   AZBB6.1  AZBB6-25          XQ  2021-08-28       0.00

[392 rows x 6 columns]

In [16]:
DAYSBACK = 365
VMIN_CORNER = '_H2_0P50V_BLOCK'
VNOM_CORNER = '_H2_0P65V_BLOCK'
VMAX_CORNER = '_H2_1P05V_BLOCK'
QUERY = f"""
WITH cte AS(
    SELECT LEFT(lot_id, 5) AS lot_id_base, lot_Id, wafer_Id, family_Code, tw.Calcdefs AS Sail, tw.Last_test_date AS date,
        unitcell_X AS retx, unitcell_Y AS rety, SUBSTR(parm_Label, 10,5) AS corner,
        tw.testProgramName||RIGHT(parm_Label,8) AS label, 
        parmYield as yield
    FROM DMIW.ChipParmFactR cpfr
        JOIN DMIW_SYSTEMS.TestParm tp ON tp.testParmKey = cpfr.testParmKey
        JOIN DMIW_SYSTEMS.Geography g ON g.geographyKey = cpfr.geographyKey
        JOIN DMIW_SYSTEMS.TestedWafer tw ON tw.testedWaferKey = cpfr.testedWaferKey
    WHERE Last_test_date >= (current date - {DAYSBACK} days)
        AND Tech_id = '7HPP' AND Level = 'H2' AND tw.Calcdefs IN ('SSL11','SSL21', 'SSL31')
        AND cpfr.parmValue IS NOT null AND ABS(parmValue) < 1e25 
        AND (UCASE(SUBSTR(tp.parm_Label,6,15)) IN ('{VMIN_CORNER}','{VNOM_CORNER}'))
        AND ((unitcell_X - 1) || '_' || unitcell_Y NOT IN ('5_12','6_12','7_12','8_12','4_11','10_11','3_10','11_10','2_9','12_9','2_4','12_4','3_3','11_3','4_2','10_2','5_1','6_1','7_1','8_1'))
        AND SUBSTR(tp.parm_Label,5,1) = RIGHT(tw.testProgramName,1)
        --AND RIGHT(tp.parm_Label,7) IN ('Block26','Block27','Block28')
        --AND family_Code = 'XQ'
        AND family_Code = 'X2'
    ORDER BY lot_Id, wafer_Id, parm_Label
),
cte2 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, corner, label, MAX(date) AS date, retx, rety, MIN(yield) AS yield
    FROM cte
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner, label, retx, rety
),
cte3 AS(
    SELECT lot_id_base, lot_id, wafer_id, family_code, label || ' ' || corner AS label, MAX(date) AS date, AVG(yield) AS yield
    FROM cte2
    GROUP BY lot_id_base, lot_id, wafer_id, family_code, corner, label
)

SELECT *
FROM cte3
"""
df = ibmdata.isdw.query(QUERY)
df['yield'] = df['yield'].astype(float).round(2)
#df['vmin_loss'] = df['vmin_loss'].astype(float).round(2)

In [15]:
df.to_csv('~/Downloads/asddf.csv')